---
- Are you:
  - afraid of:
    - going outside at night
    - going outside
    - being alone at home
    - the dark
  - religious
  - a follower of our holy lord and savior Dambara Ruru
  - an introvert or extrovert
  - a fan of:
    - Dambara Ruru
    - K-Pop
    - J-Pop
    - Anime
    - Manga
    - Comics
    - Linux
    - any celebrities

- Can you:
  - cook
  - dance
  - draw
  - kill people
  - sew
  - draw
  - ice skate
  - roller skate
  - sing
  - crochet
  - play:
    - any:
      - sports
    - baseball
    - soccer
    - basketball
    - the:
      - guitar
      - piano
      - saxophone
      - trumpet
      - bass guitar
      - drums
      - melodica
      - flute
  - ski
  - speak more than one language
  - swim
  - yodel

- Do:
  - you:
    - have:
      - a nickname
      - any:
        - celebrities who you admire, and if so, why
        - siblings
        - pets
        - unique features or qualities
        - favorite relative(s) and why
    - like:
      - muffins
      - pasta
      - social networks
      - the place where you live
      - your current job, if you have one
      - your current school, if you're a student
      - to:
        - travel
        - sing out loud when no one else is around
        - read:
          - magazines
          - novels
          - fanfiction
          - poetry
      - video games
    - prefer:
      - yuri or yaoi
    - prefer to:
      - browse the Internet on your phone, computer, or another device
      - live in a house or an apartment/flat
      - take baths or showers
      - watch movies or read books
      - read books digitally or physically
      - listen to music digitally or through physical media
    - recycle
    - think that late is better than never
    - take notes in a physical or digital notebook
    - blog
    - read:
      - books
      - manga
      - comics
      - magazines
      - online articles
      - blog posts
      - from an RSS reader
    - journal
    - want:
      - more:
        - friends
        - money
        - things than you need
        - of something you collect
      - old times back
      - to know more:
        - about:
          - history
          - new inventions
          - technology
          - Linux
          - the Internet
          - your:
            - future
            - relatives
            - friends
    - collect:
      - CDs
      - DVDs
      - comics
      - trading cards
      - books
      - magazines
      - albums
      - dolls
      - clothes
      - stamps
      - anything niche/unique
  - your:
    - friends:
      - know:
        - [much, too much]:
          - about:
            - you
            - your:
              - family
              - friends
              - hobbies
              - life
              - interests
      - like:
        - muffins
        - cats
        - social networks
        - video games
        - you the way you are
        - Dambara Ruru
        - Linux

- Have you ever:
  - been:
    - caught:
      - cheating
      - doing things you shouldn't do
      - stealing:
        - from stores
        - code
    - mistaken for someone else
    - to:
      - Australia
      - Austria
      - Brazil
      - Bulgaria
      - China
      - Czechia
      - Finland
      - France
      - Germany
      - Italy
      - Japan
      - Mexico
      - Monaco
      - Norway
      - Poland
      - Russia
      - Slovakia
      - Slovenia
      - Sweden
      - Switzerland
      - Ukraine
      - Venezuela
      - the:
        - USA
        - United Kingdom
  - had an accident
  - listened to:
    - classical music
    - drum and bass
    - dubstep
    - synthpop
    - hardstyle
    - J-Pop
    - K-Pop
    - Dambara Ruru
    - AKB48
    - black metal
    - symphonic metal
    - power metal
    - metal
    - nightcore
    - punk rock
    - trance
    - vaporwave
    - music:
      - "from the 50's"
      - "from the 60's"
      - "from the 70's"
      - "from the 80's"
      - "from the 90's"
      - "from the 2000's"
  - pet:
    - a bat
    - a bnuuy
    - a bunny
    - a cat
    - a dog
    - a dragon
    - a ferret
    - a fox
    - a horse
    - a lion
    - a mouse
    - a raccoon
    - a rat
    - a shark
    - a wolf
    - an owl
  - ridden a horse
  - written:
    - a love letter
    - code
      - in:
        - Ruby
        - Python
        - Scratch
        - C
        - C++
        - Rust
        - JavaScript
        - Perl
        - Go
    - in:
      - Arabic
      - Chinese
      - Japanese
      - Russian
    - fanfiction
    - poetry
    - original fiction
  - deployed:
    - servers

- How:
  - fast:
    - can you run
    - can you type on:
      - a:
        - computer
        - phone
        - tablet
    - is your internet connection
  - has your day been
  - often do you:
    - cook
    - eat food not prepared by yourself
    - iron your clothes
    - take selfies
    - shower/bathe
    - write
    - read
    - watch:
      - TV shows
      - movies
      - TikToks
      - YouTube videos
  - many:
    - followers is too many
    - open tabs do you currently have
    - pets do you have
  - old are you
  - did:
    - you:
      - get into j-idols or k-idols, and if you're not into them, what's your exposure/experience with them

- If:
  - you:
    - aren't book smart, what are you smart in
    - became a minor deity, what would your domain be
    - could:
      - be any fantasy creature, what would you be
    - were:
      - a Pokemon gym leader, what type would you be and what's your pokemon team like in this scenario
      - an idol, what would your image color/lightstick color be
      - given the power to enact one change on the timeline permanently & without anyone knowing it was you, how would you use this power to improve things
      - transported to the world of your current top fandom, what would you do
    - woke up as a billionaire (jeff bezos, elon musk, etc.) for a day, how would you spend their money
  - could:
    - only drink one liquid for the rest of your life, what would it be
  - your:
    - favorite color ceased to exist, what would be your new favorite color

- What:
  - [activity, activities]:
    - do you enjoy the most
  - apps do you use daily
  - do you:
    - do:
      - for a living
      - for fun
      - on the weekend
      - when you have nothing to do
    - like more,:
      - dogs or cats
      - shower or bath
      - tea or coffee
    - think about:
      - cats
      - dogs
      - dragons
      - unicorns
      - '"fact" accounts'
      - society
      - surveillance
      - the Internet
    - usually:
      - do when you're bored
      - have for breakfast
      - have for lunch
  - habit do you really find cute in a person
  - song has been stuck in your head
  - is:
    - "heavier: a kilogram of steel, or a kilogram of feathers"
    - one thing you would like to become better at
    - one thing you suck at
    - a:
      - hairstyle that suits you well
    - the:
      - [best, worst]:
        - fast food chain
        - fanfiction trope
        - trend in one of your communities
        - thing:
          - about:
              - society
              - the Internet
              - your:
                - country
                - favorite:
                  - book
                  - movie
                  - series
                - hometown
          - ever
          - one can do if they're bored
          - that happened today
        - way to prepare and eat eggs
      - weirdest thing that happened today
    - your:
      - dream job
      - current style of dress vs your dream wardrobe
      - least favorite type of humor
      - weirdest allergy if you have any
      - favorite:
        - activity
        - animal
        - beverage
        - board game
        - book series
        - console
        - food
        - Internet browser
        - language
        - name
        - number
        - song right now
        - programming language
        - season
        - snack
        - sports team
        - text editor
        - type of cheese
        - video game
        - way to eat a potato
        - website
        - comic series
        - song
        - album
        - art piece
        - scent/smell
        - type of humor
      - first memory
  - kind of animals do you have
  - languages do you know
  - was:
    - the:
      - best day of your life like
      - [best, worst]:
        - thing you've eaten so far
      - last:
          - concert you've been to
          - song you listened to
          - song you listened to on repeat
          - video game you played
          - TV show you watched
          - manga, manwha, comic, or webtoon you read
          - thing you:
            - ate
            - bought
            - did
            - looked for
    - your favorite song:
      - as a kid
      - from a few weeks ago
      - in high school
      - in college
  - would you do if you:
    - had:
        - one dollar
        - one billion dollars
        - one million dollars
        - the ability to fly
    - were a cat
    - woke up with:
      - some drawings in your face
      - someone else next to you
      - a random new cat

- When:
  - you:
    - play games (where you can customize your avatar/player), do you tend to play more femme characters or more masc characters

- Which food do you:
  - hate
  - love

- Who is:
  - the most famous person you have met
  - a:
    - celebrity you hate that is liked and why
    - celebrity you like that is hated and why
  - your:
    - oshi
    - kami-oshi
    - ni-oshi
    - ult bias
    - ult group
    - bias
    - bias wrecker
    - rival
  - your favorite:
    - spring user
    - actor/actress
    - artist
    - comedian
    - musician
    - idol
    - character

- Why do:
  - people:
    - climb mountains
    - deploy servers
    - code
    - code in:
      - C
      - C++
      - JavaScript
  - printers never work when you need them
  - they call it oven when you of in the cold food of out hot eat the food

- Would you:
  - eat a cactus
  - be the final person in a horror movie
  - rather:
    - be the best player on a horrible team or the worst player on a great team
    - live in:
      - a city or in the countryside
    - lose an arm or a leg
